name: Android Sample CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Panda3D
      run: |
        pip install https://buildbot.panda3d.org/downloads/68f0931f43284345893a90d5bba9ba5df8aa53bb/panda3d-1.11.0.dev2480-cp38-cp38-manylinux1_x86_64.whl
    
    - name: Download Panda3D [android_arm64]
      uses: wei/wget@v1
      with:
        args: -O android/panda3d-1.11.0-cp38-cp38-android_arm64.whl https://rdb.name/panda3d-1.11.0-cp38-cp38-android_arm64.whl
    
    - name: Download Panda3D [android_armv7a]
      uses: wei/wget@v1
      with:
        args: -O android/panda3d-1.11.0-cp38-cp38-android_armv7a.whl https://rdb.name/panda3d-1.11.0-cp38-cp38-android_armv7a.whl
    
    - name: Download Panda3D [android_x86_64]
      uses: wei/wget@v1
      with:
        args: -O android/panda3d-1.11.0-cp38-cp38-android_x86_64.whl https://rdb.name/panda3d-1.11.0-cp38-cp38-android_x86_64.whl
    
    - name: Download Panda3D [android_x86]
      uses: wei/wget@v1
      with:
        args: -O android/panda3d-1.11.0-cp38-cp38-android_x86.whl https://rdb.name/panda3d-1.11.0-cp38-cp38-android_x86.whl

    - name: Install Compiler Tools
      run: |
        pip install google
        pip install protobuf

    - name: Compile Sample Application
      run: |
        python setup.py bdist_apps

    - name: Upload artifacts (Build)
      uses: actions/upload-artifact@v2
      with:
        name: Build Directory
        path: build/*

    - name: Upload artifacts (dist)
      uses: actions/upload-artifact@v2
      with:
        name: Dist Directory
        path: dist/*